### ISSUE TITLE
Support for ranges

### ISSUE THREAD

**Issue by wobba** [koalamer/conust#2]
Say you want items between -12 and 200, any suggestions on how to achieve this. I assume some use of wildcards in strings could work.

**Comment by koalamer** [comment]
If you have a set of conust encoded string values, and you are trying to get those that are in the specified range, all you have to do is to encode the lower and the upper bound numbers into conust encoded strings as well (-12 to "3xyx~", 200 -> "732"), and use the resulting strings as the lower and upper bound when filtering the string set.
Or if I misunderstood the question, please elaborate...

**Comment by wobba** [comment]
My case is a search engine where I can have millions of results, and I want top 10 between a range.

On a text field that won't work so figured maybe wildcards has to be used somehow.

`Sales=3x*` etc to match all possible tokens between those two numbers. As fetching all results, sort then grab the right ones is not doable in memory.

Similar to SQL in a way. Had it been numbers I could do `TOP 10 WHERE Sales>-12 AND Sales<200 ORDER BY Sales DESC`. How would I in SQL get those items using tokens and not number fields.

Does this explain it better? And awesome solution btw 🙂

**Comment by koalamer** [comment]
If it were in a database, the solution I described earlier would work. For example:
`SELECT encoded_field FROM the_table WHERE encoded_field >= '3xyx~' AND encoded_field <= '732' ORDER BY encoded_field LIMIT 10;`
The only thing to keep in mind is to put an index on `encoded_field `field for performance reasons.

The same should also work in a text search engine. I used the precursor of Conust with Solr, with no problems.
If there is an index on the field that supports range queries, it should work the same as in the SQL case above.
If the field has only an inverted index, then (AFAIK) the search engine has to expand the list of tokens that match the range, and then search for that list. In my case there weren't millions of tokens matching a range, so that was no problem. If this is the case for you, and you have millions of range matching tokens, then yeah, I don't think that will work.

I would suggest to make sure your field supports range queries (has the appropriate indexing type) and then you don't have to deal with the high number of range matching tokens manually. Instead it will (or at least should) be handled by the search engine the same way it is when using the same query type on numbers.
Or if the original field cannot be touched, maybe move/copy the relevant tokens into a separate field that does support range queries.

With Conust you can generate strings that can be compared and ordered based on the numerical value of the original string, but to facilitate an efficient search on the resulting strings is the job of the database/search engine that stores the encoded strings. It should be possible if the field is indexed appropriately. I hope this helps.

**Comment by koalamer** [comment]
PS: Having a prefix in the the text field is no problem of course, the range condition should work with `encoded_field >= 'sales=3xyx~' AND encoded_field <= 'sales=732'` as well.

**Comment by wobba** [comment]
Except my backend cannot compare if a string/text is larger or smaller than another, and doing so in post filtering is too expensive. Appreciate your response and I'll see what I can piece together 🙂

**Comment by koalamer** [comment]
Good luck!
